### ISSUE TITLE
Task Queue error in unit tests running on PhantomJS

### ISSUE THREAD

**Issue by stevies** [aurelia/task-queue#10]
Trying to unit test a simple custom element.

```
export class BrainDeadSimple {
  msg = 'hello';
}
```

with test:

```
import {BrainDeadSimple} from 'src/resources/elements/brain-dead-          simple/brain-dead-simple';
import {BindingEngine} from 'aurelia-binding';
import {Container} from 'aurelia-dependency-injection';
import {TemplatingEngine} from 'aurelia-templating';
import {TaskQueue} from 'aurelia-task-queue';

describe('BrainDeadSimple', () => {

  let testee;
  let templatingEngine;
  let container;     

  beforeEach(() => {
    container = new Container();
    templatingEngine = container.get(TemplatingEngine);        
    testee = templatingEngine.createViewModelForUnitTest(BrainDeadSimple);
  });

  it('should set msg', () => {
    expect(testee.msg).toBe('hello');
  });
});
```

results in error:

```
Error: Error invoking TaskQueue. Check the inner error for details.
inner error: TypeError: 'undefined' is not a constructor (evaluating 'new     (window.MutationObserver || window.WebKitMutationObserver)(callback)')
```

Not sure I need task queue imported here, but did that anyway to try to fix the error.  

I am initialising the DOM elsewhere in code with: 

```
import {initialize} from 'aurelia-pal-browser';
initialize();
```

**Comment by sylvain-hamel** [comment]
I have the same issue.

**Comment by stevies** [comment]
I can work around this problem OK by using Chrome instead of Phantomjs when running karma tests.  However, have also started using Wallaby.js inside Intellij - and get the same problems.  Wallaby uses Phantomjs - so that is expected.  I can live with this for now.

**Comment by EisenbergEffect** [comment]
We know how to fix this. I've got it on my list.

**Comment by stevies** [comment]
Thanks.  No intention to hassle you about this - no rush at my end - I know you'll get around to fixing it.  Just adding comment about Wallaby in case anyone was searching for the issue.
