### ISSUE TITLE
Remarks/Questions task-queue

### ISSUE THREAD

**Issue by jods4** [aurelia/task-queue#12]
I was reading the `task-queue` source code and the following questions/remarks came to my mind. Sorry if it's irrelevant or plain wrong :no_mouth: 

(1) why doesn't `task-queue` use `setImmediate` for scheduling when it can (IE)? That should be the most lightweight and efficient way when it's supported. I thought maybe you wouldn't use it at all, but in the same file, `onError` makes use of it.

(2) is it expected that the micro- and macro- queues race with one another? 
I kind of would have expected this: `tq.queueTask(x); tq.queueMicroTask(y);` to result in `y` being executed before `x` but it isn't necessarily the case (in fact, the ordering is unpredictable, even when written `tq.queueMicroTask(y); tq.queueTask(x)`).
One can find lots of other funny cases. For instance: when processing the macro- queue, any micro-task enqueued would not be executed before all already enqueued macro-tasks have completed.

Maybe it's the way it's supposed to be, but then the doc is a bit misleading `Queues a task on the micro task queue for ASAP execution.`.

(3) the flush methods appear as public API surface (not starting with an underscore, even present in the `.d.ts` definition). But they are not written in a robust way for public API. `flushMicroTaskQueue()` is not re-entrant and may result in duplicate code execution. `flushTaskQueue()` _is_ re-entrant but may result in out of order execution.
You put the responsibility of non-reentrancy on the caller, but it's very difficult to know in arbitrary code whether you are executing inside a queue flush or not.

(4) Overall I'm wondering if we wouldn't need a priority queue here? That's what other systems have usually (see Windows/.net). Thus we could have a single structure with multiple priority (binding, rendering, idle). Seems more flexible and probably more robust to me.

**Comment by EisenbergEffect** [comment]
I think this is good feedback. Thank you.
1. I can't remember exactly why setImmediate isn't used in that case, but I seem to recall there was indeed an issue.
2. Perhaps we should enforce that the macro task queue always flushes the micro task queue first?
3. Any interest in submitting a PR to improve this?
4. I think you may be right about this. I've been trying to avoid it. It would have been more difficult when we had Object.observe in the mix, but now that that is gone it might be time to revisit it.

Specifically on points 3 and 4, would you be interested in helping to do some of that work and submitting PRs? I believe they both can be accomplished in non-breaking ways. The queue methods can take an optional 2nd param indicating the priority, which could fall back to "normal" if not provided. Ultimately, we need @jdanyow 's opinion on this since this is likely to affect the binding library more than anything else.

**Comment by jods4** [comment]
@EisenbergEffect I think I might find some time to tackle this, if @jdanyow approves the changes.

If I go for a priority queue, what kind of public API breakage is allowed?
If there was no compat. concerns, the API would be something like:

``` typescript
enqueue(task, priority = normal);
flush();
```

Do you think we have to keep the old ones? I think usage of flush was dangerous and pretty unlikely.
If we want to keep old functions for compat we could map `queueMicroTask` to `enqueue(task, "binding")` as this was the main usage of micro tasks; and probably map `queueTask` to `enqueue(task, "normal")`. 

If we don't want to keep too much history but at the same time limit breakage we could keep `queueTask` as a method name instead of `enqueue`. Unfortunately it seems `queueMicroTask` could have been more popular (but makes no sense in a priority queue).

Opinions?

**Comment by EisenbergEffect** [comment]
We would need to keep existing methods. We could map them internally as you recommend. That's probably the way to go.

@jdanyow When you get freed up, I'd love to hear your opinions.

**Comment by jdanyow** [comment]
Maybe `setImmediate` was a node related thing? There are some comments here that might be relevant: https://github.com/kriskowal/asap/blob/master/raw.js#L86-L91

Couple thoughts/questions on the API changes:
1. Could we remove queueTask altogether? Nothing in Aurelia uses it that I could see. Personally I would favor doing that instead of complicating the logic to ensure the micro queue flushes before the macro, etc, etc.
2. The priority thing sounds useful. Just need to make sure whatever data structure is used doesn't increase memory pressure. We can add benchmarks for the task-queue as-needed.

**Comment by jods4** [comment]
@jdanyow comments say that on NodeJS `setImmediate` is slower than `nextTick`... but that's a Node thing, there's no `nextTick` in the browser. In fact, `setImmediate` is only supported by IE (and Node), so if it's available it's most probably the best choice. Unless there is another reason? Maybe a race condition with some Promise completion?

I have been thinking and doing some research in Aurelia code base. 

I am not as sure as before that having a central priority queue is that useful. The issue is that there are too many unrelated "queues" in the browser that we just can't control.

I/O events, whether user input, ajax, file & co. are in the browser realm.
Layout: internal to the browser, opaque and no access.
Rendering: best bet is `requestAnimationFrame`, `CSS transition` or the future animation APIs.
Promises: have their own "Job" which is a microqueue, according to next ES specs.

Users that want to schedule work "next turn" usually think of using Promises or `setTimeout` or `setImmediate` before Aurelia's `TaskQueue`.

All that's left in the end is the binding engine... So I suggest we just keep things simple and avoid a general priority queue, because I don't see much use for it, sadly.

I have reviewed Aurelia's own usage of the task queue. As @jdanyow said I couldn't find usage of the macro `queueTask`. 

`queueMicroTask` falls broadly in three categories:
- Handling observed changes on the next turn (what I expected).
- Updating the UI later. Several components do stuff like this, although I am not 100% sure why:
  https://github.com/aurelia/templating-resources/blob/0a9300210920e10791c47ab6f1c117b879c5ebe8/src/if.js#L48
  What is the motivation here?
- Preventing circular code execution... but that tickled me so I'll open another issue to discuss it separately.

Also, sometimes the queue is not injected globally, for example here:
https://github.com/aurelia/binding/blob/86722faf435ca9b667c28d0ced4235b06c88e30c/src/checked-observer.js#L40
`this.observerLocator.taskQueue.queueMicroTask(this);`
This is just a memory optimization, right? Or are there multiple queues running inside Aurelia?
Of course in theory there could be several queues but it's important that users know which queue they should use to wait for bindings to settle.

My conclusion is that we should probably keep a single queue, which is used for change notification.
I think that it is important though that users have a way to perform stuff when the queue is "idle", i.e. when all changes have settled down.

To avoid breaking changes we can keep `queueMicroTask` for mostly internal, fast-loop usage and `queueTask` for public, after bindings usage. I can fix the existing code so that this contract is properly enforced.

**Comment by jdanyow** [comment]
sorry- didn't mean to confuse things, what I meant was the `setImmediate` stuff might be a remnant from the code's cross-platform origins. It's non-standard so we probably don't want to use it.

> - Updating the UI later. Several components do stuff like this, although I am not 100% sure why: https://github.com/aurelia/templating-resources/blob/0a9300210920e10791c47ab6f1c117b879c5ebe8/src/if.js#L48 What is the motivation here?

here's the issue for ^^^:  https://github.com/aurelia/templating-resources/issues/84

**Comment by jods4** [comment]
@jdanyow 
I saw that most code here was lifted from ASAP and there are interesting comments over there about `setImmediate` usage.
Basically `setImmediate` is a good choice where it's available (IE) but they had non-fairness issues on some platforms (notably mobile and IE10 I think), whereas a very busy system would not execute `setImmediate` code before all `setTimeout` occurrences have been processed (i.e. not at all if you `setTimeout` like crazy).
It seems to me that's really edge cases as a system that busy would be unresponsive anyway... But I don't know any better :stuck_out_tongue: 

Overall with all the different mechanisms in place to orchestrate deferred work (`setTimeout`, `setImmediate`, `Promise`, Aurelia task queue, async call such as `XMLHttpRequest`), it's hard to guarantee any execution order.

I read aurelia/templating-resources#84 and kinda grasp the issue.
The resolution seems a bit hacky to me.
Would having more than 2 priority in the queue help/solve such issues more cleanly? Maybe `binding`, `UI`, `idle`?
What do you think on that matter?
I want to be sure we have the right design before doing any code change.

**Comment by jdanyow** [comment]
wow- on a hunch I imported the plunker from the original issue report in aurelia/templating-resources#84, updated to the latest aurelia build and removed the taskqueue usage in the `if` template controller. Turns out the TaskQueue is no longer needed: https://gist.run/?id=995d61c259bd17f8ed97

Must be we fixed or improved something in all the binding and repeat changes and testing since July.

I will put together a PR that removes the task queue from `If`. 

@jods4 without your review we probably never would have seen this... thank you for the lending another set of :eyes: !

**Comment by jods4** [comment]
Cool, althgouh I'm not sure I fully understand the implications here :confused: 

Note that there are other usage of `queueMicroTask` that I would consider "UI" level.

Model change in `compose`:
https://github.com/aurelia/templating-resources/blob/eddec88849aac66247d05567b20fec9a30cb572d/src/compose.js#L105

Giving focus in `focus` (I think I see why, maybe this one is special):
https://github.com/aurelia/templating-resources/blob/e31310f3b455e33237e587f86f67e385103ffbef/src/focus.js#L45

So if the UI composition does not use the task queue, I guess the existing two levels (micro-task = changes propagation; task = after everything updated) are sufficient?

**Comment by jdanyow** [comment]
@jods4 any updates on this- should we keep it open?

**Comment by jods4** [comment]
@jdanyow Sorry for not coming back at this. I have been overwhelmed by work and I lost track of this.
Right now I'm going to travel for 1 month so don't expect a PR from me any time soon.

In all cases, I think the points (2) and (3) and the initial ticket should be fixed.
(2) defeats the purpose of multiple queue "speed" and will break in the face of computed properties or cascading dependencies.
(3) is probably more rare but dangerous.

For those reasons I would keep this open until someone (me or someone else) fixes at least those two points.

**Comment by padzikm** [comment]
Can you explain how MicroTaskQueue is flushed at the end of each tick? I'm reading source code and there is only makeRequestFlushFromMutationObserver function, which manually triggers flushing the queue, but nowhere else in code it isn't used, nor observed node is changed to trigger flush.

**Comment by jdanyow** [comment]
It's called from the queueMicroTask method

**Comment by padzikm** [comment]
Yes, but only when microTaskQueue is empty. When tasks are queued the condition is false and flush is not triggered - so when is it flushed?

```
TaskQueue.prototype.queueMicroTask = function queueMicroTask(task) {
      if (this.microTaskQueue.length < 1) {
        this.requestFlushMicroTaskQueue();
      }
      this.microTaskQueue.push(task);
    };
```

**Comment by jdanyow** [comment]
That code means the first task pushed onto an empty queue will schedule the flush.  The flush will happen at the end of the "turn".

**Comment by padzikm** [comment]
Oh, how could I missed that...thank you for quick answer
