### ISSUE TITLE
promised tasks

### ISSUE THREAD

**Issue by obedm503** [aurelia/task-queue#22]
**I'm submitting a feature request**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Linux - KDE Neon 5.12

* **Node Version:**
9.6.1

* **NPM Version:**
5.6.0

* **Yarn Version:**
1.3.2

* **JSPM OR Webpack AND Version**
webpack 4.0.1

* **Browser:**
all
* **Language:**
all

**Current behavior:**
`TaskQueue#queueMicroTask` just takes a function/`Task` and returns `void`
```ts
queueMicroTask(task: Task | Function): void;
```
**Expected/desired behavior:**
`TaskQueue#queueMicroTask` takes a function/`Task` and returns `Promise<void>` which resolves when the task is called.
```ts
queueMicroTask(task: Task | Function): Promise<void>;
```
* **What is the motivation / use case for changing the behavior?**
there are times when I need 2 separate "tasks" to happen but I need the first task's side effects (binding, `valueChanged` functions, etc) to settle down, before registering the second one's side effects.

currently the way to achieve this is to register the task that has side effects, and from inside that task register the second task.

some pseudocode:
```ts
@autoinject
class Page {
  constructor(private taskQueue: TaskQueue){}

  someMethod(){
    // wait for side effects to settle down
    this.taskQueue.queueMicroTask(() => {
      this.someProp = 5;

      // wait again
      this.taskQueue.queueMicroTask(() => {
        this.focusNextElementInForm();
      });
    });
  }
}
```
and if we wanted to have more things happen in succession, we would quickly find ourselves in callback hell. the same process written using `async`/`await` is much more readable
```ts
@autoinject
class Page {
  constructor(private taskQueue: TaskQueue){}

  async someMethod(){
    // wait for side effects to settle down
    await this.taskQueue.queueMicroTask(() => {
      this.someProp = 5;
    });
    // wait again
    await this.taskQueue.queueMicroTask(() => {
      this.focusNextElementInForm();
    });
  }
}
```

to achieve this behavior i'm overriding the `TaskQueue#queueMicroTask` method, with something along the lines of:
```ts
const oldQueueMicro = TaskQueue.prototype.queueMicroTask;
TaskQueue.prototype.queueMicroTask = function queueMicroTask(task) {
  return new Promise((resolve, reject) => {
    try {
      oldQueueMicro.call(this, () => {
        task.call();
        resolve();
      });
    } catch (e) {
      reject(e);
    }
  });
};
```
it works, but it's not the best

**Comment by Alexander-Taran** [comment]
is it any different from 
```
await Promise.resolve().then(() => firstTask())
  .then(()=>nextTask() )
  .then(()=>continueWithMadness())
```

**Comment by obedm503** [comment]
If I understand the micro task and promises correctly and assuming firstTask, nextTask, and continueWithMadness register tasks,
1. They run on different queues in relationship to the event loop
2. Wrapping them in Promise.resolve will do nothing special because there's nothing that tells the next promise to wait to register the next task. So that is the same as registering them one after another

And if your question refers to not using Task queue: I specifically NEED to use the task queue because of it's relationship to the rest of the Aurelia framework

**Comment by Alexander-Taran** [comment]
Well in my meta code I thought of  `firstTask()` and the rest as actual tasks.. 
So chain of .then() actually ensures consecutive execution of those.

You also can  `async () => { await firstTask() }`   where first task returns a promise..
But well.. Need is a Need.

can you provide a pull request for this?

**Comment by StrahilKazlachev** [comment]
@obedm503 simply said, you want to know when a task you've registered has executed?
Bear in mind that any over-engineering of the `TaskQueue` may lead to negative performance impact.

**Comment by obedm503** [comment]
@StrahilKazlachev yes, so that I can register another task for the next flush. and yes, simply making it always return a promise might also not be the best solution, maybe making a new method on the `TaskQueue` to handle this?

**Comment by StrahilKazlachev** [comment]
Why for the next flush? When calling `queueMicroTask` from within a micro task, the new task goes at the end of the current queue, which is being flushed, so it is executed in the current flush.
Also the tasks in the queue are executed synchronously.

**Comment by StrahilKazlachev** [comment]
Also since it is a queue and you want the tasks to run in a succession, why not:
```js
queue.queueMicroTask(() => {/* Task A */});
queue.queueMicroTask(() => {/* Task B */});
// ...
queue.queueMicroTask(() => {/* Task N */});
```

**Comment by obedm503** [comment]
> Also since it is a queue and you want the tasks to run in a succession, why not:

because I might do things that trigger side effects again and want to wait for them to finish before continuing

**Comment by Alexander-Taran** [comment]
**MicroTask**
what are you really sticking in there @obedm503 ?

**Comment by obedm503** [comment]
@Alexander-Taran already explained above

**Comment by Alexander-Taran** [comment]
@obedm503 well not clear enough
For me at least.
I don't understand why you want it to be on microTasksQueue.
Just because it exists?
There is no concrete example from you.
What are you using it for.
And it looks like "you are holding it wrong" so far.
Sorry

**Comment by CasiOo** [comment]
@StrahilKazlachev's example will have the exact same effect as your `await` example @obedm503.
The only difference is that you won't be able to use `await` or promises.

In my opinion we should not introduce a try-catch for each callback in the queue since it might have a negative impact on performance.

**Comment by obedm503** [comment]
yes, it might be better to make it a separate method, so that if you don't care about using promises and don't mind callback hell, you can do that

@Alexander-Taran the use case is so that it's easier to do things that run after each flush of the micro task, but need the side effects to run before continuing. It **has** to be on the micro task queue so that I can hook on to aurelia, if not there's no way to know when binding is done.

**Comment by CasiOo** [comment]
So you would like a new async method? I would have liked the `async` postfix, but it might indicate that queuing the task is async
```
queueAsyncMicroTask(task: Task | Function): Promise<any> {
  return new Promise((resolve, reject) => {
    this.queueMicroTask(() => {
        try {
          task.call();
          resolve();
        } catch (e) {
          reject(e);
        }
    });
  });
}
```

**Comment by 3cp** [comment]
**Update: latest PR merged API to `queueMicroTask(task, priority = queuePriority.normal)`**

My PR proposed a new api `taskQueue.jumpQueueMicroTask(task)`.

Comparing to the proposed promise api here, `taskQueue.jumpQueueMicroTask(task)` has extra freedom to be called anywhere in your code, not limited to explicit call of `taskQueue.queueMicroTask()`.

Note: when flushing micro/macro tasks, there is zero delay (no setTimeout) between the tasks. If you queue two micro tasks `do1()` and `do2()`, they will be executed just like `do1(); do2();` in one shot.

With the new api, you can do
```js
someMethod(){
  this.taskQueue.queueMicroTask(() => {
    /* do some thing */

    this.taskQueue.jumpQueueMicroTask(() => {
      // immediate execution after the parent micro task
      // before the rest of micro tasks in queue
    });

    /* do more things */
    // it would not make much sense if you don't have more code
    // to be executed after the above call
  });
}
```

This makes more sense:
```js
// when someMethod is called by aurelia during flushing micro task queue.
someMethod() {
  // when it's not flushing micro task queue, jumpQueueMicroTask behaves
  // same as queueMicroTask
  this.taskQueue.jumpQueueMicroTask(() => {
    // immediate execution after current running micro task,
    // before the rest of micro tasks in queue
  });
}
```

**Comment by EisenbergEffect** [comment]
We've decided to skip this feature for now. One reason is that we've found a way to remove the need for a microtask queue at all in vNext by enabling synchronous bindings to model updates and a more powerful component lifecycle. In light of that, I'm not sure we want to enhance this module in preparation for it to basically become obsolete.
