### ISSUE TITLE
Throwing error in setImmediate terminates Electron renderer process!

### ISSUE THREAD

**Issue by timfish** [aurelia/task-queue#23]
The following code [from here](https://github.com/aurelia/task-queue/blob/f427668061a750fb6ff7b59ee8ebc9aabe4a9c31/dist/native-modules/aurelia-task-queue.js#L43:L45) causes the Electron renderer process to terminate:
```
setImmediate(function () {
  throw error;
});
```

This can easily be reproduced in Electron 1.8.6 by pasting the following into the renderer console:
```
window.setImmediate(() => {throw new Error('Test')})
``` 

In the main process console you will sometimes get the following:
```
Error: async hook stack has become corrupted (actual: 558, expected: 0)
```

I'm currently bodging this with the following code although this is far from ideal:
```
window.setImmediate = (m) => window.setTimeout(m, 0);
```

**Comment by timfish** [comment]
The crashing issue is specific to Electron before the latest v2.0.0 although its still probably better not calling node `setImmediate`.

**Comment by EisenbergEffect** [comment]
I agree. Your change is merged in and will be released in the next batch. Thanks!
