### ISSUE TITLE
Micro optimization

### ISSUE THREAD

**Issue by fkleuver** [aurelia/task-queue#26]
Been playing around with this a little bit. 5 different approaches to `requestFlush()`. They all behave the same (trigger a mutation in `MutationObserver` in all major browsers), but the performance - however ridiculously small - is different.

**1. toggle + toString (vNext)**
```js
let toggle = 1;
let node = document.createTextNode('');
...
toggle = -toggle;
node.data = toggle.toString();
```

**2. toggle (vCurrent)**
```js
let toggle = 1;
let node = document.createTextNode('');
...
toggle = -toggle;
node.data = toggle;
```

**3. Object lookup swap**
```js
let val = 'a';
let node = document.createTextNode('a');
let values = Object.create(null);
values['a'] = 'b';
values['b'] = 'a';
...
node.data = val = values[val];
```

**4. Array toggle (creds to jods)**
```js
let values = ['a', 'b'];
let toggle = 0;
...
node.data = values[toggle ^= 1];
```

**5. Coerce mutation**
```js
node.data = 0;
```

Benchmark: http://jsben.ch/EEXsx

**Chrome**
![image](https://user-images.githubusercontent.com/9655331/41209106-88e632a6-6d29-11e8-9bd2-a7cc29a91896.png)

**Edge**
![image](https://user-images.githubusercontent.com/9655331/41209116-a5df827c-6d29-11e8-95ed-c9eb8521f69e.png)

**Firefox**
![image](https://user-images.githubusercontent.com/9655331/41209135-c0aa145a-6d29-11e8-987d-ccd96a85be64.png)

Notes:

- Chrome > FF > Edge in performance
- Everything is slow in Edge
- Bitwise ops, indexers and lookups are fast in Chrome
- Indexers are slow in FF, coercion is fast in FF
- Edge is really slow
- Chrome is really fast
- FF always surprises me

If it weren't for FF, I would have gone with jods' approach. I thought indexers had more overhead in Chrome too but apparently I was wrong.
I'm leaning more towards the lookup swap because `= 0` just feels like it's not very spec-esque (works, but will it keep working?)

Of course, no one will ever notice the difference. Doesn't make it any less fun to experiment with these things now and then :)

Thoughts/preferences/don'ttouchit?
@bigopon  @EisenbergEffect

**Comment by bigopon** [comment]
Well, @jdanyow told me once every bit counts, guess we keep the culture ?

Firefox nightly 2018-06-10

![nightly 62 0a1](https://user-images.githubusercontent.com/9994529/41210447-1b5dff38-6d75-11e8-8536-c95830221191.png)

**Comment by EisenbergEffect** [comment]
Seems like the object lookup swap might be the good balanced improvement. It's faster than the current and vNext implementations in all browsers, it's not an odd solution and it gets good performance in FF.

**Comment by RomkeVdMeulen** [comment]
Has anyone taken a look at the performance of [window.queueMicrotask](https://caniuse.com/#feat=mdn-api_windoworworkerglobalscope_queuemicrotask) yet (where available)?

**Comment by fkleuver** [comment]
Last time I checked, its performance was precisely identical to that of `Promise.resolve().then`, both of which are a *tiny* bit faster than the mutation observer trick we're using here.

However, the timing of `queueMicroTask` is not guaranteed to be identical to the mutation observer mechanism and that in itself would be enough reason not to risk it for v1.
Also, we stepped away from using micro tasks in v2 in the framework itself (and for the public scheduler api we're using `Promise.resolve().then`, just due to availability / for consistency)
