### ISSUE TITLE
Can't load in a node environment

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/task-queue#5]
Assumes `window` is present which isn't the case in a node environment.
This line https://github.com/aurelia/task-queue/blob/master/src/index.js#L1 crashes when trying to load the module.

**Comment by zewa666** [comment]
@stoffeastrom sry that nobody replied to your issue. From the perspective of Aurelia this module is meant solely for use in the browser, as indicated by the readme. One thing you could try though is to use something like jsdom and see if it works with that.

**Comment by EisenbergEffect** [comment]
@zewa666 I spoke to @stoffeastrom about this. He's reporting these issues for me. We want to get all of Aurelia working in Node, even if it isn't rendering on the server.

**Comment by zewa666** [comment]
OK thats cool :+1:

**Comment by stoffeastrom** [comment]
:). With some monkey patching I actually was able to run unit tests in node for a _custom attribute_ which is quite nice! I haven't tried loading all modules in node yet so most likely there are a couple of more places but as long as we report them we keep track of it

**Comment by EisenbergEffect** [comment]
I think we've got this covered via the pal now.
